name: workout_app
description: "Workout app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  percent_indicator: ^4.2.5
  google_fonts: ^6.3.3
  flutter_riverpod: ^3.0.3
  http: ^1.6.0
  hive_ce: ^2.5.0
  hive_ce_flutter: ^1.1.0
  hive_ce_generator: ^1.1.0
  flutter_svg: ^2.0.9
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo1.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"
